### ISSUE TITLE
Registering of Debug Panel does not work.

### ISSUE THREAD

**Issue by patrickkusebauch** [contributte/cache#11]
I understand that 0.5 version is in dev, but just to let you know.

It will generate (when configured as described in the docs )following code in DI container:
```php
	public function createServiceTracy__bar(): Tracy\Bar
	{
		$service = Tracy\Debugger::getBar();
		if (!$service instanceof Tracy\Bar) {
			throw new Nette\UnexpectedValueException('Unable to create service \'tracy.bar\', value returned by factory is not Tracy\Bar type.');
		}
		addPanel('cache.debug.tracy.panel');
		return $service;
	}
```

This code will when run produces: `Error: Call to undefined function addPanel()`.

**Comment by f3l1x** [comment]
Fixed in v0.6 using https://github.com/contributte/cache/commit/d603189e6bf97d2d3d182ff98bfe6aef85a5c07c
